### ISSUE TITLE
Cannot use ouster-sdk alongside mayavi

### ISSUE THREAD

**Issue by Karthikeyanc2** [ouster-lidar/ouster_example#302]
Hello,

I want to use ouster client and mayavi in parallel. I am able to install them, although not able to import them together, If I import mayavi mlab first, ouster client could not be imported, also, if I import ouster client first, I am not able to import mayavi. Please see the attached test images

**Installation:**

```
(base) C:\Users\AININ_G1>conda create -n ouster_mayavi_test python=3.7

(base) C:\Users\AININ_G1>conda activate ouster_mayavi_test

(ouster_mayavi_test) C:\Users\AININ_G1>pip install ouster-sdk

(ouster_mayavi_test) C:\Users\AININ_G1>conda install -c menpo mayavi --force

```

**Test 1**
Importing mayavi mlab first
```
(ouster_mayavi_test) C:\Users\AININ_G1>python
Python 3.7.10 | packaged by conda-forge | (default, Sep 13 2021, 19:12:52) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from mayavi import mlab
>>> from ouster import client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\AININ_G1\anaconda3\envs\ouster_mayavi_test\lib\site-packages\ouster\client\__init__.py", line 4, in <module>
    from ._client import SensorInfo
ImportError: DLL load failed: The specified procedure could not be found.
>>> exit()
```

**Test 2**
Importing ouster client first
```
(ouster_mayavi_test) C:\Users\AININ_G1>python
Python 3.7.10 | packaged by conda-forge | (default, Sep 13 2021, 19:12:52) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from ouster import client
>>> from mayavi import mlab
Traceback (most recent call last):
  File "C:\Users\AININ_G1\anaconda3\envs\ouster_mayavi_test\lib\site-packages\vtkmodules\vtkIOParallel.py", line 5, in <module>
    from .vtkIOParallelPython import *
ImportError: DLL load failed: The specified procedure could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\AININ_G1\anaconda3\envs\ouster_mayavi_test\lib\site-packages\mayavi\mlab.py", line 16, in <module>
    from mayavi.tools.camera import view, roll, yaw, pitch, move
  File "C:\Users\AININ_G1\anaconda3\envs\ouster_mayavi_test\lib\site-packages\mayavi\tools\camera.py", line 24, in <module>
    from .engine_manager import get_engine
  File "C:\Users\AININ_G1\anaconda3\envs\ouster_mayavi_test\lib\site-packages\mayavi\tools\engine_manager.py", line 13, in <module>
    from mayavi.core.registry import registry
  File "C:\Users\AININ_G1\anaconda3\envs\ouster_mayavi_test\lib\site-packages\mayavi\core\registry.py", line 16, in <module>
    from mayavi.core.metadata import Metadata, import_symbol
  File "C:\Users\AININ_G1\anaconda3\envs\ouster_mayavi_test\lib\site-packages\mayavi\core\metadata.py", line 11, in <module>
    from mayavi.core.pipeline_info import PipelineInfo
  File "C:\Users\AININ_G1\anaconda3\envs\ouster_mayavi_test\lib\site-packages\mayavi\core\pipeline_info.py", line 12, in <module>
    from .utils import get_tvtk_dataset_name
  File "C:\Users\AININ_G1\anaconda3\envs\ouster_mayavi_test\lib\site-packages\mayavi\core\utils.py", line 2, in <module>
    import vtk
  File "C:\Users\AININ_G1\anaconda3\envs\ouster_mayavi_test\lib\site-packages\vtk.py", line 32, in <module>
    all_spec.loader.exec_module(all_m)
  File "C:\Users\AININ_G1\anaconda3\envs\ouster_mayavi_test\lib\site-packages\vtkmodules\all.py", line 83, in <module>
    from .vtkIOParallel import *
  File "C:\Users\AININ_G1\anaconda3\envs\ouster_mayavi_test\lib\site-packages\vtkmodules\vtkIOParallel.py", line 9, in <module>
    from vtkIOParallelPython import *
ModuleNotFoundError: No module named 'vtkIOParallelPython'
>>> exit()
```

Kindly let me know how to solve this issue, I have to go with mayavi because it simply satisfies all plotting functionality requirements.

Thank you,
Karthik

**Comment by Karthikeyanc2** [comment]
Hello, 
The issue was with Mayavi, Now it works
Thanks
